name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build the Docker Compose stack
      run: docker compose up -d
    
    - name: Check running containers
      run: docker ps -a
    
    - name: Run tests
      run: docker compose run app npm test
    
    - name: Stop containers
      if: always()
      run: docker compose down